### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by martinrebo** [martinrebo/boilerplate#12]
**TASKS: **
- [x] 🧪  Create more tests for components > elements
- [x] 🎨 Improve UI/UX on the main pages (Axpel - Exercise 1 and 2 ) 
- [x] 🐛 Fix Axpel> Search bar > "not defined Location dispatch to Redux"
- [ - ] 🐛 Fix .env variable on Cloud Build for npm packages version
- [x] 🐛 Fix express (google app engine) serve static files for SPA.  
- [x] ✨ Create / Fix navigation bar for the current pages
- [ ] ♻️ Clean Redux Store (delete / comment messages store ) 
- [ ] 🔐 Hide and revoke API keys (mongo + Google API) 
- [ ] 🔏 Update Dependencies from dependabot
- [x] 📄 Add React / Node Best practices to Docs and Guides Readme File
